name: Deploy Thumbnail Generator Lambda
on:
  push:
    branches:
      - main
    paths:
      - src/**/*
      - .github/workflows/deploy-lambda.yml

defaults:
  run:
    working-directory: src/

jobs:
  terraform:
    name: 'Deploy Thumbnail Generator Lambda'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.22.0'

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build Lambda
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/main .

      - name: Zip build
        run: zip -r -j main.zip ./build

      - name: Update Lambda code
        run: aws lambda update-function-code --function-name=thumbnail-generator --zip-file=fileb://main.zip
